apiVersion: apps/v1
kind: Deployment
metadata:
  name: ief-deployment
spec:
  strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
        maxSurge: 0
  replicas: 1
  selector:
    matchLabels:
      app: ief
  template:
    metadata:
      labels:
        app: ief
    spec:
      nodeSelector:
        kubernetes.io/hostname: minikube
      containers:
      - name: ief
        image: gabriel0murilo/ief:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: output-volume
          mountPath: /app/output
        resources:
          limits:
            nvidia.com/gpu: 1  # Usa 1 GPU
      volumes:
      - name: output-volume
        hostPath:
          path: /output  # pasta local (no node)
          type: Directory
