name: CI/CD - Teste + Build Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Instalar dependências e rodar tudo
        env:
          CI: "true"
        run: |
          python3 -m pip install --upgrade pip
          pip install pytest
          bash setup.sh