name: CI/CD - Teste + Build Docker
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalar dependências
        run: |
          sudo apt-get update && sudo apt-get install -y gdal-bin
          pip install -r requirements.txt
      - name: Rodar testes
        run: pytest -p no:faulthandler
